config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only:[:show, :new, :create]
  resources :users
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

	has_many :post_categories
	has_many :posts, through: :post_categories

  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true

  sluggable_column :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  
end 

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories 

  validates :title, presence: true, length: {minimum: 3}, uniqueness: true
  validates :url, presence: true 
  validates :description, presence: true

  sluggable_column :title
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

	has_many :posts
	has_many :comments
  has_many :votes

  has_secure_password validations: false
  validates :name, presence: true, length: {minimum: 3}, uniqueness: :true
  validates :password, presence: true, on: :create, length: {minimum: 8}

  before_save :generate_slug
  sluggable_column :name

# Code related to role
  def admin?
    self.role == "admin"
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: :voteable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def set_categories
    @categories = Category.all
  end

  #these two are used to control the UI
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  # this used to shut down the actions that from the url.
  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in."
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "You can't do that"
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:show]
  before_action :set_categories
  before_action :require_admin, only: [:new, :create]

  def show
    @category = Category.find_by(slug: params[:id])  
    @posts = @category.posts
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Succesfully created"
      redirect_to posts_path
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  before_action :set_categories

  def create
    # This are only for the create action. 
    # In order to display the form I need to define the Objects in the show action.
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    # this line is equivalent of saying 
    #@comment = Comment.new(params.require(:comment).permit(:body))
    #@comment.post = @post
    @comment.creator = current_user
    if @comment.save
      flash[:notice] = "You comment was posted!"
      redirect_to post_path(@post)
    else
      @categories = Category.all
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(creator: current_user, voteable: @comment, vote: params[:vote])
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show,:edit,:update, :vote]
  before_action :set_categories

  before_action :require_user, except:[:index, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @posts = Post.all
  end

  def show
    # this new comment I have to set in order for the show action to show it.
    # I do not need to define the @post because it's already defined.
    @comment = Comment.new
    # params is a hash where all the request info is stored.
    # So it basically takes all the info from one action to the other
    # @post = Post.find(params[:id])
  end

  def new

    # this post has to be defined only if we are using 
    # the backend -forms because we need to pass it to
    # the form so that it knows what object are we talking about
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to post_path(@post)
    else
      # render does not count as new request
      # so @post.errors stored in here are passed to the new view
    render :new
    end
  end

  def edit
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(creator: current_user, voteable: @post, vote: params[:vote])
    respond_to do |format|
        format.js
    end
  
  end
  # here starts the strong params definition.
  private

  def post_params
    # Strong parameters are there just to regulate what parameter are mass updated
    # Require is tells the data base what params are needed 
    # Permit tells which are allowed for mass updating
    # The constructions params.require(:post) assumes a nested structure
    params.require(:post).permit! 
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_same_user
    if current_user != @post.creator and !current_user.admin?
      flash[:error] = 'Your are not allowed to modify that!'
      redirect_to post_path(@post)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_categories
  def new
    
  end

  def create
    user = User.where(name: params[:name]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully logged in.'
      redirect_to root_path
    else
      flash[:error] = 'Your user-name or password do not match.'
      redirect_to login_path  
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only:[:edit, :update]
  before_action :set_categories
  

  def new
    @user = User.new
  end

  def create
    @user = User.new(set_params)

    if @user.save
      flash[:notice] = "Your account was successfully created"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end

  end

  def show
    @posts = @user.posts
  end

  def edit
    
  end

  def update
    if @user.update(set_params)
      flash[:notice] = 'Your profile was successfully updated'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_params
    params.require(:user).permit(:name, :password, :time_zone)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = 'Your are not allowed to modify that!'
      redirect_to user_path(@user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def fix_date(obj)
    obj.created_at.strftime("%b %d, %Y")
  end

end

app/views/categories/_category.html.erb
<span class='badge'><%= category.name %></span>

app/views/categories/new.html.erb
<%= render 'shared/errors', obj: @category %>

<h3>Would you like to create a new Category?</h2>

<div class="well">
  <%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <%= f.submit "Create category", class: 'btn btn-primary' %>
  <%end%>
</div>

app/views/categories/show.html.erb
<% posts_link = link_to("All Posts", posts_path)%>

<%= render 'shared/title', title: "#{posts_link} &raquo #{@category.name}".html_safe %>

<%= render 'shared/posts' %>

app/views/comments/vote.js.erb
$('#comment_<%=@comment.id%>_votes').html('<%=@comment.total_value%> votes')

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <!--Remove toggle and caret for a normal nice-looking button -->
  <div class="btn-group">
    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <% @categories.each do |cat| %>
          <li><%= link_to cat.name, category_path(cat)%></li>
      <% end %>
      <% if logged_in? && current_user.admin?%>
        <li class="divider"></li>
        <li><%= link_to(new_category_path) do%>
          <i class="icon-plus"></i>
          Create Category
        <%end%>
        </li>
      <% end %>
    </ul>
  </div>

  <% if logged_in? %>

  <div class="btn-group ">
    <%= link_to(new_post_path) do %>
      <button class="btn btn-small btn-success"><i class="icon-plus"></i> New Post!</button>
    <%end%>
  </div>

    <div class="btn-group nav-item">

      <button class="btn btn-small dropdown-toggle" data-toggle="dropdown"> <%=current_user.name%> <span class="caret"></span></button>

      <ul class="dropdown-menu">
        <li>
          <%= link_to(edit_user_path(current_user)) do%>
            <i class = 'icon-pencil'></i>
            edit profile
          <% end %>

          <%= link_to(user_path(current_user)) do%>
            <i class = 'icon-user'></i>
            view profile
          <% end %>

          <%= link_to(logout_path) do%>
            <i class = 'icon-circle-arrow-left'></i>
            log out
          <% end %>

        </li>
      </ul>
    </div>

  <% else %>

    <div class="btn-group">
      <%= link_to(new_user_path) do %>
        <button class="btn btn-success"><i class="icon-plus"></i> New User!</button>
      <%end%>
    </div>

    <div class="btn-group">
      <%= link_to(login_path) do %>
        <button class="btn">Log in</button>
      <%end%>
    </div>

  <% end %>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<div class="well">
  <%= form_for @post do |f| %>
    <%= f.label :title %>
      <%= f.text_field :title %>
      <br/>
      <%= f.label :url %>
      <%= f.text_field :url %>
      <br/>
      <%= f.label :description %>
      <%= f.text_area :description%>
      <br/>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cat|%>
        <%=cat.label(class: 'checkbox inline') {cat.check_box() + cat.text } %>
      <%end%>
      <br/>
      <br/>
      <% if posting == true %>
        <%= f.submit "Post!", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Update!", class: "btn btn-primary" %>
      <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/errors', obj: @post %>
<h3>Make some changes</h3>

<%= render 'form', posting: false %>

app/views/posts/index.html.erb
<%= render 'shared/title', title: 'All Post' %>

<%= render 'shared/posts' %>

app/views/posts/new.html.erb
<%= render 'shared/errors', obj: @post %>

<%= render 'shared/title', title: 'Create New Post' %>

<!--
PURE HTML
<form action="/posts" method="POST">
  Title <input type="text" name="title"><br>
  URL <input type="text" name="url"><br>
  Description <input type="text" name="description"><br>
  <input type="submit" value="Submit">
</form> 
-->
 <%= render 'form', posting: true %>

app/views/posts/show.html.erb
<!-- Remember that this is the render property in rail that
iteraters through all the post.categories and applies the _category style to it-->
<%= render 'shared/categories', obj: @post.categories %> 
<!-- Renders the Shared/title and pass in the value @post.title to be replace
in the variable title -->
<% if logged_in? && (current_user == @post.creator || current_user.admin?)%>
  <p class="pull-right">[<%= link_to "Edit Post", edit_post_path(@post) %>]</p>
<%end%>
<%=render 'shared/title', title: @post.title  %>

<p><%= @post.description%></p>
<hr/>

<%= render 'shared/errors', obj: @comment %>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body  %>
    <%= f.text_area :body, :required => true %>
    <br/>
    <%= f.submit "Post Comment", class: "btn btn-primary" %>
  <% end %>
  <hr></hr>
<% end %>

<h3><%= @post.comments.size%> Comments</h3>
<hr/>

<%= render 'shared/comments', obj: @post.comments, display_source: false %>

app/views/posts/vote.js.erb
$('#post_<%=@post.id%>_votes').html('<%=@post.total_value%> votes')

app/views/shared/_categories.html.erb
<% obj.each do |cat| %>
  <span class='badge'><%=link_to cat.name, category_path(cat) %></span>
<% end %>

app/views/shared/_comments.html.erb
<% obj.each do |comment| %>
  <div class="row">

    <div class="well span0 text-center">
      <% if logged_in? %>
        <%= link_to(vote_post_comment_path(comment.post,comment, vote: true), method: 'post', remote: true) do %>
          <i class = 'icon-arrow-up'></i>
        <% end %>
        <br/>
      <% end %>
      
      <span id='comment_<%=comment.id%>_votes'><%=comment.total_value%> votes</span> 
      
      <% if logged_in? %>
        <br/>
        <%= link_to(vote_post_comment_path(comment.post,comment, vote: false), method: 'post', remote:true) do %>
          <i class = 'icon-arrow-down'></i>
        <% end %>
      <% end %>
    </div>

    <div class="well span8">
      <em><%=comment.body  %></em>

      <% if display_source %>
        on <%= link_to comment.post.title, post_path(comment.post)  %>
      <% end %>
      
      <p><span class ='quiet'>by</span> <%=link_to comment.creator.name, user_path(comment.creator) %> <small> at <%=fix_date(comment)%></small></p>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-error">
    <ul>
      <%obj.errors.full_messages.each do |msg|%>
        <li><%=msg %></li>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_posts.html.erb
<% @posts.each do |post| %>
  <div class='row'>

    <div class="well span0 text-center">
    <% if logged_in? %>
      <%= link_to(vote_post_path(post, vote: true), method: 'post', remote: true ) do %>
        <i class = 'icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>
      <span id='post_<%=post.id%>_votes'><%=post.total_value%> votes</span>
    <% if logged_in? %>
      <br/>
      <%= link_to(vote_post_path(post, vote: false), method: 'post', remote: true) do %>
        <i class = 'icon-arrow-down'></i>
      <% end %>
    <% end %>
    </div>

    <div class="well span8">
      <%= render 'shared/categories', obj: post.categories %>
      <h4><%= link_to post.title , fix_url(post.url) %></h4>  
      <p><%= post.description%></p>
      <p><span class ='quiet'>posted by</span> <%=link_to post.creator.name, user_path(post.creator)%> <small> at <%=fix_date(post)%></small></p>
      <small><%=link_to "#{post.comments.size} comments", post_path(post) %></small> 
    </div>
  </div>
<% end %>

app/views/shared/_title.html.erb
<p class ='lead'><%=title%></p>
<hr></hr>

app/views/users/_form.html.erb
<div class="well">
  <%=form_for @user do |f|%>
    <div class="control-group">
    <%=f.label :name%>
    <%=f.text_field :name %>
    </div>
    <div class="control-group">
    <%=f.label :password%>
    <%=f.password_field :password%>
    </div>
    <div class="control-group">
      <%=f.label :time_zone%>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
    </div>
    <%=f.submit class: 'btn btn-primary'%>
  <%end%>
</div>

app/views/users/edit.html.erb
<%= render 'shared/title', title: @user.name %>
<%= render 'shared/errors', obj: @user %>
<%= render 'form'%>

app/views/users/new.html.erb
<%= render 'shared/title', title: 'Sign Up!'  %>
<%= render 'shared/errors', obj: @user %>
<%= render 'form'%>

app/views/users/show.html.erb
<% if logged_in? and current_user == @user %>
<p class="pull-right">[<%= link_to "Edit Profile", edit_user_path(@user) %>]</p>
<% end %>
<%=render 'shared/title', title: @user.name %>

<div class="well">
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd><%=@user.name%></dd>
    <dt>Time zone:</dt>
    <dd><%=@user.time_zone%></dd>
  </dl>
</div>

<ul class="nav nav-tabs">
  <li class = '<%= 'active' if params[:tab].nil? %>'>
    <%=link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>

  <li class = '<%= 'active' if params[:tab] == 'comments' %>'>
    <%=link_to "Comments (#{@user.comments.size})", user_path(@user, tab:'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <%=render 'shared/posts'%>
<% else %>
  <%= render 'shared/comments', obj: @user.comments, display_source: true %>
<% end %>